### PR TITLE
generate actions

### PR DESCRIPTION
**Pull request by querdenker2k**

### CODE REVIEW

**Comment by querdenker2k** [comment]
This is generating the actions via the compiler to be typo-safe.

**Comment by querdenker2k** [comment]
What i did: 
- moved all generated stuff from items folder to gen folder
- changed package for all generated stuff from */items/generated, */things/generated to */generated/items, */generated/things
- add generated actions to */generated/actions
- add all possible actions for a binding which provides actions
- changed some logging from "items and things" to "generated sources"
- added a test with sending an mqtt message

**Comment by seaside1** [comment]
I'll check it out.

**Comment by seaside1** [comment]
Great will test it out.

**Comment by seaside1** [comment]
I'm getting failures in the tests:

`ERROR] Failures: 
[ERROR]   JRuleActionClassGeneratorTest.testGenerateAndCompileActionFile:75->generateAndCompile:114 Failed to generate source file for org.openhab.core.thing.internal.ThingImpl@9eedeea9 ==> expected: <true> but was: <false>
[ERROR]   JRuleItemClassGeneratorTest.testGenerateAndCompileGroupItem:98->generateAndCompile:155 Failed to generate source file for ColorGroup (Type=GroupItem, BaseType=ColorItem, Members=0, State=NULL, Label=ColorGroupLabel, Category=null) ==> expected: <true> but was: <false>
[ERROR]   JRuleItemClassGeneratorTest.testGenerateAndCompileStandardItem:80->generateAndCompile:155 Failed to generate source file for ColorItem (Type=ColorItem, State=NULL, Label=ColorItemLabel, Category=null) ==> expected: <true> but was: <false>
[ERROR]   JRuleItemClassGeneratorTest.testGenerateItemsFile:124->generateAndCompile:155 Failed to generate source file for SwitchItem (Type=SwitchItem, State=NULL, Label=SwitchLabel, Category=null) ==> expected: <true> but was: <false>
[ERROR]   JRuleThingClassGeneratorTest.testGenerateAndCompileThingFile:71->generateAndCompile:112 Failed to generate source file for org.openhab.core.thing.internal.ThingImpl@9eedeea9 ==> expected: <true> but was: <false>
[ERROR]   JRuleThingClassGeneratorTest.testGenerateThingsFile:85->generateAndCompile:112 Failed to generate source file for org.openhab.core.thing.internal.ThingImpl@9eef7804 ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 9, Failures: 6, Errors: 0, Skipped: 0
`

**Comment by seaside1** [comment]
23:02:49.911 [main] ERROR o.o.a.j.a.JRuleActionClassGenerator - [JRuleActionClassGen] Internal error when generating java source for action mybinding:thingtype:id: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> action.type  [in template "actions/ActionJavadoc.ftlh" at line 4, column 66]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

**Comment by querdenker2k** [comment]
Damn, sorry. Forget to disable skipTests. Testcase is corrected.

**Comment by seaside1** [comment]
Quick fix, i will test it. 👍

**Comment by seaside1** [comment]
Still get failures in tests: 

```
ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.024 s <<< FAILURE! - in org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest
[ERROR] org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.testGenerateThingsFile  Time elapsed: 0.01 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Failed to generate source file for org.openhab.core.thing.internal.ThingImpl@9eef7804 ==> expected: <true> but was: <false>
	at org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.generateAndCompile(JRuleThingClassGeneratorTest.java:112)
	at org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.testGenerateThingsFile(JRuleThingClassGeneratorTest.java:85)

[ERROR] org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.testGenerateAndCompileThingFile  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Failed to generate source file for org.openhab.core.thing.internal.ThingImpl@9eedeea9 ==> expected: <true> but was: <false>
	at org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.generateAndCompile(JRuleThingClassGeneratorTest.java:112)
	at org.openhab.binding.jrule.internal.JRuleThingClassGeneratorTest.testGenerateAndCompileThingFile(JRuleThingClassGeneratorTest.java:71)

```

**Comment by querdenker2k** [comment]
don't know what i build, but it was not right.
Now its really working. There was some more failures in the testclasses.

**Comment by querdenker2k** [comment]
nice, you added an ci build?

**Comment by seaside1** [comment]
Yes, was not sure it would check current open PRs, but it seems like it did.

**Comment by seaside1** [comment]
This seems to work. Tested it out with Pushover.

**Pull request merged**
