### PR TITLE
add Actions (openhab internal), rename old Actions to ThingActions

### PR DESCRIPTION
**Pull request by querdenker2k**
This PR will
- rename generated JRuleActions to JRuleThingActions
- generate JRuleActions (based on all found ActionService's, e.g. Notifications from openhabcloud)

### CODE REVIEW

**Comment by querdenker2k** [comment]
oh damn, looks like. i saw your merge request, but never opened it and couldn't imagine what that meant based on the title.
The approach is slightly different.
I used ActionService and you used ActionType.
Your's is still in progress? Can i try it?

**Comment by seime** [comment]
I forgot a bit about the pr myself, but I've been running it in production since this summer without issues. Ready for testing.

Not sure which approach is best, I'll need to read the code again to freshen my memory 😅.

**Comment by jberggg** [comment]
I'm running @seime 's changes for broadcast notifications through openhab "cloud". It works 👍🏽  Would be awesome if that feature makes it into the main branch.  Thank you both for your work 🙏🏽

**Comment by seime** [comment]
@querdenker2k should we merge this or the other PR and get the functionality out to everyone?

**Comment by querdenker2k** [comment]
If yours is working we can take yours (and because some more people used this in production). I used mine not productive because of the problem that the iphone app does not support two service instances like the android app.

**Pull request closed without merging**
