### PR TITLE
forNameOptional, UnspecifiedGroupItem, QuantityItem

### PR DESCRIPTION
**Pull request by querdenker2k**
added:
- forNameOptional (not throwing an exception)
- UnspecifiedGroupItem (Groups which contains different Item types)
- QuantityItem to just handle NumberItem with Quantity
- NumberItem is not allowed to handle Quantities
- fix in JRuleSwitchGroupItem
- typesafe memberItems() for each specific GroupItem
- changed the Unit parameter for Quantity sendCommand/postUpdate to String (having trouble with OSGI, ClassNotFound at runtime)

### CODE REVIEW

**Review by seime — COMMENTED** [review]
README should be updated

**Comment by querdenker2k** [comment]
> README should be updated

done, add example forNameOptional

**Comment by seime** [comment]
Needs a new rebase after merging the previous PR

**Review by seime — COMMENTED** [review]
Findings so far:

- I think we should allow sending double/int to QuantityItems as well (without a unit)
- Persistence functions for QuantityItems are missing (ie averageSince)

At a later time when the openhab maintainers agree on how quantity types actually should be defined and handled, we should do some refactorings (ie get the  persistence functions typed, be aware of the default unit when sending unspecified values etc)

**Review by seime — APPROVED** [review]

**Pull request merged**
