### PR TITLE
Add addonaction handler

### PR DESCRIPTION
**Pull request by querdenker2k**
adds the option to use addon actions like telegram.

This is an usage example:
```
var telegram = getAction("telegram", "telegram:telegramBot:telegram");
telegram.doAction("sendTelegram", "test");
```

### CODE REVIEW

**Comment by seime** [comment]
As an initial generic solution I think it is good as it opens up calls to any(?) action from JRule.

But one of the reasons I have switched to JRule is strong typing and being able to catch errors at compile time and not runtime.

Could we look at the possibility to use the code generator to generate a `JRuleAction` + `JRuleActions` class along the lines of `JRuleItem`/`JRuleItems`? Then we could add code like

`JRuleActions.telegram_telegramBot_telegram.sendTelegram("my message")`

to the rules?

WDYT @seaside1 ?

**Comment by querdenker2k** [comment]
That sounds even nicer. I will try something...

**Comment by seime** [comment]
@querdenker2k I've done some refactoring in the code generator that you should be aware of, see PR https://github.com/seaside1/jrule/pull/59

**Comment by querdenker2k** [comment]
@seime Do you know when this will be ready for merge that i can work on this?
Or is it a state where i can merge this in my branch?

**Comment by seime** [comment]
It is functioning - at least on my system and have been running smooth for a few weeks, but I think we *should* to do some refactoring on JRuleEvent before or after merging. as the class was built for item events - and not channel trigger events, timed events nor thing events.

Keeping in mind that you have suggested (and I applaude) some refactoring on execution contexts, JRuleWhen annotation, and the actions functionality, I'd *personally* prefer if this PR was merged first - or I will have a merge hell ;)

I think @seaside1 would need to make the decision.

**Comment by querdenker2k** [comment]
I thing as well that all open (working) merge request should be merged as well before do the refactoring.

**Comment by seaside1** [comment]
I think this is great. I have created a branch and code using script-actions to do this, but I never got it to work fully, and the solution itself was quite bad IMO.

This proposal to generate actions is much better.

**Comment by seaside1** [comment]
I've tested this with pushover, seems to work fine!
Merging, will do an update of the doc with example

**Comment by seime** [comment]
@querdenker2k Now that the thing support is merged, would you give the code generator approach a try?

**Comment by querdenker2k** [comment]
Yes, I am evaluating it. But it would be nice if the JRuleWhen MR will be merged first. It's a lot of manual merge otherwise.

**Pull request merged**
