### PR TITLE
support channel events as rule trigger

### PR DESCRIPTION
**Pull request by roth**
Hi @seaside1. Thats my first shot to support channel events as rule trigger. What do you tink? Any comments / suggestions?

Thanks a lot!

### CODE REVIEW

**Comment by roth** [comment]
I'm not sure about the further direction: Should it be also possible to process https://www.openhab.org/docs/configuration/rules-dsl.html#thing-based-triggers?

The problem with https://www.openhab.org/docs/configuration/rules-dsl.html#channel-based-triggers is that they can't be easily linked to an item (for thing-based-triggers this is possible) - the only workaround I found is, to update an item in a traditional rule and then react on that item change with a JRule... this was the main motivation for this PR.

**Comment by seaside1** [comment]
@roth  Nice work! I'll review this more closely and test it out, but looks good at first glance. About thing-based triggers, I'm not sure, I guess it depends if you think you or someone else would need them ? 

Could you "tag" a rule with an annotation for which item is linked to the channel trigger (to solve the problem with linking a trigger channel to an item)? That would maybe work, like:

``java
    @JRuleName("channelTriggered")
    @JRuleWhen(channel = "binding:thing:buttonevent", item=_MyCoolItem.ITEM)
    public synchronized void channelTriggered(JRuleEvent event) {
	logInfo("Channel triggered with value: {}", event.getValue());
    }
```

/S

**Comment by seaside1** [comment]
Nice work!

I have merged it. I tested it out with astro binding, seems to work fine.
Possibly we could add the value as a condition in the annotation.

So, we have for instance:

    @JRuleName("channelTriggered")
    @JRuleWhen(channel = "astro:sun:local:set")
  public synchronized void channelTriggered(JRuleEvent event) {
        logInfo("ASTRO: Channel triggered with value: {}", event.getValue());
    }


It could be:
    @JRuleName("channelTriggered")
    @JRuleWhen(channel = "astro:sun:local:set", trigger = START)
  public synchronized void channelTriggered(JRuleEvent event) {
        logInfo("ASTRO: Channel triggered with value: {}", event.getValue());
    }

Which would mean the rule would only be triggered if the trigger has the value start.

**Comment by roth** [comment]
Thanks a lot @seaside1 for merging that quickly! I will think about your input - Thanks!

**Pull request merged**
