### PR TITLE
added annotation as method is part of dynamic rule

### PR DESCRIPTION
**Pull request by kuimovvg**
What do you think about slightly changing the approach to declaring and creating dynamic rules?

### CODE REVIEW

**Comment by seaside1** [comment]
I think that would work. I will test it out shortly.

**Comment by seaside1** [comment]
The problem I see with this is that the annotations makes it not be fully dynamic. If you look at the implementation I made for the sonos-jrule, I have dynamic trigger for items as well. I think we could add this but it should not replace the existing dynamic load.

**Comment by kuimovvg** [comment]
I agree, he is also needed. Inattentively I looked at the functionality from sonos-jrule. Return the addDynamicWhenReceivedCommand method in my PR?

**Comment by seaside1** [comment]
@kuimovvg Sorry for being absent. Worklife has been hectic lately. I would like to merge the original dynamic rules PR first, and then test this out.

**Pull request closed without merging**
