### PR TITLE
Fix parsing of double value when QuantityType is used 

### PR DESCRIPTION
**Pull request by seime**
... as annotation comparator parameter

### CODE REVIEW

**Comment by seaside1** [comment]
But this will be for more than just no QuantityTypes? I have not tested this myself but will QuantityType print a similar error message?

**Comment by querdenker2k** [comment]
Why are the openHAB classes are all mapped at all?
Why not use the openHAB classes directory especially the types/states?

**Comment by seaside1** [comment]
@querdenker2k  Initially I started with that, to have full control and minimize dependencies. Also it's a bit more clear what is beloging to jrule and what is core. I realize that using the coretypes could would have worked, it is just a choice to try out with the mapped classes.

This is something we could change, if we want to. I feel the strong typing is a good idea, it's really simple to develop rules I have to say.

**Comment by seime** [comment]
I'd also prefer to use the core classes (states and commands) directly and avoid mappings if possible.

**Comment by seaside1** [comment]
I'm not against it. Main drawback for me is that it requires more deps as a rule developer but that's maybe not a big one.
Also the core classes tend to be a bit diverging from each other. But yes will def remove a lot code where mapping between types are done.

So it's quite a big refactoring to do, I guess  it could be done incrementally  if we want to do it.

**Pull request merged**
