### PR TITLE
[WIP] Generate Items file 

### PR DESCRIPTION
**Pull request by seime**
Update: Code from #41 merged in here

---
This is the start of a bigger change.

The idea is to be able to refer to items by the corresponding Item class (such as `JRuleSwitchItem` instead of just passing item names around, ie 
`Double state = Items.AeonUte_Battery.getState();` vs 
`Double state = JRuleNumberItem.forName(_AeonUte_Battery.ITEM).getState();`

This PR does the following changes:
- Replaces the templating mechanism with Freemarker, mainly to allow more advanced constructs such as loops - and to avoid all the repetitive code in the template files
- Generates a new file `Items.java` which looks a bit like
```
public class Items {
 public static MySwitchItem SwitchItem = JRuleItemRegistry.get("MySwitchItem", MySwitchItem.class);
 public static MyStringItem StringItem = JRuleItemRegistry.get("MyStringItem", MyStringItem.class);
}
```

- Adds a skeleton support for LocationItem (which was missing)
- Adds a new field `LABEL` (item label)
- Adds a few convenience methods such as `getLabel()` and `getName()`
- Adds more typing of Group items
Next steps would be to 
- Go over templates again to reduce unnecessary repeats accross diffent item types

What do you think?

### CODE REVIEW

**Comment by seaside1** [comment]
Just made a brief look, will take a close look later. I was a bit worried that the Items file would be replacing the generated classes, but it seems it is more an addition that can be used, which is good I believe.
Would be good to change the name of the Items to JRuleItems (to be consistent).

I would guess it would be (for completeness):
Double state = JRuleItems.AeonUte_Battery.getState(); vs
Double state = JRuleNumberItem.forName(_AeonUte_Battery.ITEM).getState(); vs
Double state = _AeonUte_Battery.getState();

Seems like a good idea to make the templating more advanced and enhanced.

**Comment by seime** [comment]
I do not think the last one would work atm as the getState() method isn't static.

Note that there seems to be an issue with the classloading when updating items/rules runtime (maybe because there is a direct instance reference in the rule file). To be fixed

**Comment by seime** [comment]
I'll take a look at it and do some more updates to the PR

**Comment by seime** [comment]
I've thought about the static getState() a bit more, and one of the reason I've done some changes is to avoid to pass item _names_ around, but item _instances_ instead. With this comes better type safety.

I have multiple 're-used' functionality like this one; 
```
	private RollershutterStatusUpdater gShutterTerrace = new RollershutterStatusUpdater(Items.Shutter_gUte_Terrasse, 2, 38);

	@JRuleName("Terrace position tracker")
	@JRuleWhen(item = Shutter_gUte_Terrasse.ITEM, trigger = TRIGGER_RECEIVED_COMMAND)
	public void trackTerrace(JRuleEvent event) {
		gShutterTerrace.handleCommand(event.getState().getValue());
	}
```
where `RollershutterStatusUpdater` is a reusable component. By just passing the ITEM (name) it is quite easy to introduce bugs such as calling `JRuleNumberItem.forName(ITEM).sendCommand(XYZ)` - which will blow up in production because the item is of `JRuleRollershutterItem` and not `JRuleNumberItem`

**Comment by seime** [comment]
Any comments @seaside1 ?

**Comment by seaside1** [comment]
Sorry missed your comments there. Yes I agree on calling static methods on instances is a bad practice
The Double state = _AeonUte_Battery.getState();
Would be correct since you call it in a static manner. I agree on type safety.
I guess we need to decide if we want to make it more type safe, probably a good idea since we are using quite a lot of typing anyway. Reason I stick with the static call  _AeonUte_Battery.getState(); is because it seems quite simple that you don't have to have a instance, you more or less needs to remember the name. On the other hand I guess using forName and JRuleItems is also simple but a bit longer to write to express.

What do you suggest?

/S

**Comment by seaside1** [comment]
Did you push everything here? I'm getting compile errors for items.

public _MyTestItemImg(String name) {
        super(name);
    }

 constructor JRuleItem in class org.openhab.autom
ation.jrule.items.JRuleItem cannot be applied to given types;
  required: no arguments
  found: java.lang.String
  reason: actual and formal argument lists differ in length

And JRuleItem does not define a constructor.


As far as the code looks I think it is good.

**Comment by seime** [comment]
It appears Image and Call item support was missing

**Comment by seaside1** [comment]
Some of the triggers are missing. Like
JRuleSwitchItem.TRIGGER_CHANGED_FROM_ON_TO_OFF

**Comment by seaside1** [comment]
This commit is really big now? Is it ready for merge?

**Comment by seime** [comment]
Yes, I am sorry about all the changes. Kinda impossible to do major changes as separate PRs as they often do changes in the same area of code and hence depend on each other, creating a big mess.

I assume you have tested it a bit?

There are more improvements to be made, but they can be done in later PRs.

**Comment by seaside1** [comment]
This is a large merge for sure. What I would like to see is to be compatible with previous version, that is
being able to _GenerateItem.getState() and _GeneratedItem.sendCommand etc.
I think we could deprecate those methods and remove them in the future, but it might be rough to change API completely too quickly. I can give a hand in adding that if you like, I have somewhat limited time this week but could at least start.

**Comment by seaside1** [comment]
Yes I think this is the way to go. I think we could make it backwards compatible by adding some ugly methods in the the templates, but it will take some time to get working, and if we plan on deprecating them, maybe not the best way of using time.
@gerrieg  Do you have any opinion on the API changes in this PR?

I will test it out a bit more and update the documentation and then we merge it. It's great that you have put so much effort into this, big changes for sure.

**Comment by seaside1** [comment]
Loading rules/ classes from folder does not work. I'll have a look at it later

**Pull request merged**
