### PR TITLE
configurable ItemPrefix

### PR DESCRIPTION
**Pull request by weberjn**
I finished your work to make ItemPrefix configurable. I changed the templating mechanism to use ${var}s for classname and item name. Also made package configurable. I had to refactor a bit to pull the config up to JRuleFactory, so it can be injected to all consumers.

### CODE REVIEW

**Comment by seaside1** [comment]
I have started to look at this. Will test it out a bit.

**Comment by seaside1** [comment]
I have some smaller feedback, for instance keeping the JRuleEngine as a pure singleton, i'll do a separate commit for that

**Comment by seaside1** [comment]
Thank you for fixing and adding missing parts for making the generated class files configurable.

**Comment by weberjn** [comment]
You're welcome. If the templates get more complex you should change to an engine like Terence Parr's StringTemplate. Once we did an IDL2Cobol with it.

**Pull request merged**
