### PR TITLE
Allow java source files in subdirs. Add support for rule preconditions

### PR DESCRIPTION
**Pull request by seime**
This PR does 2 things (this is the diff from my fork to yours after all my PR merges - please forgive a few other minor changes)

* Allow java source files to be located in subfolders, ie not enforce all source files to exist in a flat folder structure. Allows for more organising of rule code
* Add @JRulePrecondition annotation. Often rules contain a lot of "only execute this rule if this and that item state has a certain value". By adding this to a precondition those statements can be avoided. Multiple annotations are ANDed together.

### CODE REVIEW

**Comment by seaside1** [comment]
I like the idea with preconditions. I originally looked at instead of having JRuleWhen having JRuleOr and JRuleAnd, but it became too complex with parentheses etc, so I choose to have it a bit more plain and simple.

Adding preconditions with AND seems like a good solution and makes it clear that you can for instance
have a JRulePreCondition on "SystemStarted" or "NotificationsEnabled" etc. I think we should add some examples as well to the documentation. I'll test the preconditions out before merging, going to be a bit quicker than I was before, having some downtime from this project.

BR S

**Comment by seaside1** [comment]
I have tested with:

  @JRulePrecondition(item=_MyTestSwitch.ITEM, state = "ON")
 
Which works fine, question is then if you think we should add possible values via static variables instead? Ex:
  @JRulePrecondition(item=_MyTestSwitch.ITEM, state = JRulePrecondition.ON)

I guess this will not be applicable for string, decimals and so on.

**Comment by seaside1** [comment]
I modified the code a bit, the idea is that JRuleWhen and JRulePrecondition should use the same syntax for the comparator
for instance:

@JRulePrecondition(item=_MyTestSwitch.ITEM, state = "30", comparator=EQ)
@JRuleWhen(item = _MyTemperatureSensor.ITEM, trigger = _MyTemperatureSensor.TRIGGER_RECEIVED_UPDATE, state = "30", comparator=EQ)

vs

@JRulePrecondition(item=_MyTestSwitch.ITEM, eq = "30")
@JRuleWhen(item = _MyTemperatureSensor.ITEM, trigger = _MyTemperatureSensor.TRIGGER_RECEIVED_UPDATE, eq = "30")


and 

@JRulePrecondition(item=_MyTestSwitch.ITEM, state = "30", comparator=GT)
@JRuleWhen(item = _MyTemperatureSensor.ITEM, trigger = _MyTemperatureSensor.TRIGGER_RECEIVED_UPDATE, state = "30", comparator=GT)

vs 

@JRulePrecondition(item=_MyTestSwitch.ITEM, gt = 30)
@JRuleWhen(item = _MyTemperatureSensor.ITEM, trigger = _MyTemperatureSensor.TRIGGER_RECEIVED_UPDATE, gt = 30)

Let me know what you think.

**Comment by seime** [comment]
Yes, I like the additional comparators and common syntax. 

Also I agree that building complex combinations of AND and ORs just makes the code more clumsy to read, and is best suited as regular java code inside the rule

**Comment by seaside1** [comment]
Great. Merging.

**Pull request merged**
