### PR TITLE
add MDC logging tags

### PR DESCRIPTION
**Pull request by querdenker2k**
added a new annotation: JRuleTag
within this you can define mdc tags. This is useful when logging to elasticsearch to filter just relevant stuff.

### CODE REVIEW

**Comment by seaside1** [comment]
Nice! I failed to push  some updates to your branch, want to remove the star import and changed "rule" to a static string.
[0001-Removed-import-and-fixed-a-static-string.zip](https://github.com/seaside1/jrule/files/9693235/0001-Removed-import-and-fixed-a-static-string.zip)
Added it as a patch.

(I think there is a checkbox stating "Allow edits from maintainers")

I'm going to test it out a bit. It's very nice to filter on tags.

**Comment by querdenker2k** [comment]
strange, its checked already.
added your patch.

**Comment by seaside1** [comment]
Nice. I would like to update the documentation as well. How are you using MDC in combination with elastic search? Logstash? Could be could to give a recommendation on how to use it.

**Comment by seaside1** [comment]
I'll merge it, seems to work for me, will try to get some documentation in later.

**Comment by querdenker2k** [comment]
Bildschirmfoto vom 2022-10-04 19-18-35
I attached an screenshot where the filters are visible.
I am using filebeat to receive the logs, elasticsearch to store them and kibana to filter them.

**Comment by seaside1** [comment]
Nice, I'll try to set up something similar. It is also nice to be able to search multiple logs from many openhab instances. I'm currently running 3.

**Pull request merged**
