### PR TITLE
Execute rules on a separate executor service to avoid congestion

### PR DESCRIPTION
**Pull request by seime**
Rules can take time to complete and should be run on a separate executor

### CODE REVIEW

**Comment by seaside1** [comment]
I like this idea. I will see if I can add configuration for it as well.

**Comment by No3x** [comment]
Given a rule is triggered and running. Then the rule is triggered again while the first execution is still running. The rule might run concurrently then within two threads. Hence the rule and all libs you use in it must be implemented thread-safe.

Is my understanding correct? If yes don't you think that could cause issues? 
A quick look shows that e.g. `JRuleVoiceHandler` would be shared across rules too. I might be wrong but I just wanted to share my thoughts about it.

**Comment by seime** [comment]
To be honest I did not do very deep research whether the openhab bus threads would properly ensure true parallelism. But I remember from working with the DSL rules that there is a separate thread pool for those rules. Not sure if it applies to JRule though.

If you need to ensure that a particular rule does not execute in parallell, would it not be enough to mark your method as `synchronized`?

There is no locking at all for the `JRuleVoiceHandler`, so  if all rules would execute on a single thread you still get overlaps. I've had this problem in DSL rules as well; the say() method is fire and forget, and if you do not ensure correct timing in the DSL rule, the second command would interrupt the first anyways. And it could come from any rule thread..

**Comment by seaside1** [comment]
I will add a config parameter to use the executors so you can decide yourself if you want to go that route

**Comment by No3x** [comment]
This would be nice. So we can test it and see if there are problems.

**Comment by seaside1** [comment]
I have made this configurable, default it is off to turn on set config variable org.openhab.automation.jrule.engine.executors.enable = true 
under /etc/openhab/automation/jrule/jrule.conf

## Run rules in a separate threadpool
org.openhab.automation.jrule.engine.executors.enable=false

## Minimum number of threads
org.openhab.automation.jrule.engine.executors.min=2

## Maximum number of threads
org.openhab.automation.jrule.engine.executors.max=10

**Comment by seaside1** [comment]
See https://github.com/seaside1/jrule/commit/229d5052d7119a4917a4280bd880eaf3ccdb3cac

@seime  @No3x 

I made a commit to have this as the default behavior, I've been using the threaded execution for quite some time and it seems to work as expected. Any objections/ experiences in it not working?

BR S

**Comment by No3x** [comment]
I have not used jrule since a while and did not try the setting to be honest. I did a quick test of the ThreadPoolExecutor to verify my theory:

<details>

A simple Counter that is a synonym for e.g. the JRuleVoiceHandler.
First run with  MIN_EXECUTORS 1 and MAX_EXECUTORS 1 to force no concurrency and see that the test does not fail. Then run with 2 and 10 and see it fail.

```java
import static org.assertj.core.api.Assertions.*;

import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;

import org.junit.Test;

import com.google.code.tempusfugit.concurrency.annotations.Intermittent;

public class JRuleThreadPoolExecutorTest {

  private static final int MIN_EXECUTORS = 2;
  private static final int MAX_EXECUTORS = 10;
  private ThreadPoolExecutor ruleExecutorService;

  ThreadFactory ruleExecutorThreadFactory = new ThreadFactory() {
    private final AtomicLong threadIndex = new AtomicLong(0);

    @Override
    public Thread newThread(Runnable runnable) {
      Thread thread = new Thread(runnable);
      thread.setName("JRule-Executor-" + threadIndex.getAndIncrement());
      return thread;
    }
  };

  static class MyCounter {
    private int count;
    public void increment() {
      int temp = count;
      count = temp + 1;
    }
  }

  @Test
  @Intermittent(repetition = 200)
  public void preservesOrderOfTasksScheduledWithSameDelay() throws InterruptedException {
    ruleExecutorService = new ThreadPoolExecutor(MIN_EXECUTORS, MAX_EXECUTORS, 2L, TimeUnit.MINUTES,
        new LinkedBlockingQueue<>(), ruleExecutorThreadFactory);

    int numTasks = 1_000;
    CountDownLatch countDownLatch = new CountDownLatch(numTasks);
    final MyCounter sharedObject = new MyCounter();
    for (int i = 0; i < numTasks; i++) {
      ruleExecutorService.submit(() -> {
        int before = sharedObject.count;
        sharedObject.increment();
        int after = sharedObject.count;
        countDownLatch.countDown();
      });
    }
    ruleExecutorService.shutdown(); // initiate shutdown. previously started tasks will be executed but no more tasks will be accepted
    countDownLatch.await(); // this will wait until all threads have reached
    final boolean cleanShutdown = ruleExecutorService.awaitTermination(20, TimeUnit.SECONDS);// give it max 20s to terminate
    assertThat(cleanShutdown).isTrue().describedAs("To be fair we must ensure all threads are finished. This should be technically already checked with countDownLatch but double check..");
    assertThat(sharedObject.count).isEqualTo(numTasks);
  }
}
```
</details>

In reality there might be a little thing different so there is no issue when it runs in openhab (but I can't see it). Or chances are low a rule is submitted again while it executes.

**Comment by seaside1** [comment]
Thanks for testing it out. 
I think you are right in that it is a problem in theory, and might not be an issue in practice with OpenHAB.
I will revert back the config change, so you have to enable executors manually like it was before to use it.
I'll continue to use them to see if I get any problems with them.
Any idea on how to make it more thread safe? JRuleVoiceHandler is at least running as a singleton so should be shared.

````java
  public static JRuleVoiceHandler get() {
        if (instance == null) {
            synchronized (JRuleVoiceHandler.class) {
                if (instance == null) {
                    instance = new JRuleVoiceHandler();
                }
            }
        }
        return instance;
    }
````

BR S

**Comment by No3x** [comment]
Singleton pattern with double checking and volatile looks good to me. There is only one instance but this instance is shared across threads. I have looked at one path (briefly) as example `JRuleVoiceHandler  > VoiceManagerImpl > JavaSoundAudioSink`

JRuleVoiceHandler methods don't have shared state > then openhab core is called: from here you are "done". Based on the fact that each openhab rule runs in its own thread (just found out from a thread in openhab community but not sure if it is still true) they are in the same position from here. > VoiceManagerImpl mostly no state > JavaSoundAudioSink mostly synchronized.

This sample explains to me a bit better why it does not make much trouble currently.
Is it sufficient to add `org.openhab.automation.jrule.engine.executors.enable=true` to the `runtime.cfg`?

**Comment by seaside1** [comment]
Good to have an extra pair of eyes on the problem. It is also documented how to set it: https://github.com/seaside1/jrule#configuration

I'll leave it default on then and we can see if anyone notice any problems. I'll write in the release notes that default behavior is changed to default use threads. Perhaps we should lower them a bit to min 2, max 4 as the default.

**Pull request merged**
