### PR TITLE
Memberof trigger

### PR DESCRIPTION
**Pull request by querdenker2k**
Created a memberOf option for item event triggers.
Discussed here: https://github.com/seaside1/jrule/issues/22
When setting memberOf=true on a group-item the rule will fire for all direct group member events.

### CODE REVIEW

**Comment by seime** [comment]
@querdenker2k I've added an example of how to write trigger tests in https://github.com/seaside1/jrule/pull/73 - WDYT? I'd love to get more tests in JRule as it is quite annoying to detect bugs only when my home automations quietly breaks after merging the latest code.

This PR is quite big so I expect something to break just by the sheer size of it.

**Comment by seime** [comment]
And by the way - great work! I've been waiting for this feature - it is the last missing nail in the DSL rule coffin for my setup :)

**Comment by querdenker2k** [comment]
> @querdenker2k I've added an example of how to write trigger tests in #73 - WDYT? I'd love to get more tests in JRule as it is quite annoying to detect bugs only when my home automations quietly breaks after merging the latest code.
> 
> This PR is quite big so I expect something to break just by the sheer size of it.

yes, thats really anoying. i created my docker test project for this to test JRule with the real environment as a "blockbox". Maybe we could integrate this kind of testing as well.

**Comment by seaside1** [comment]
I'm getting some failed tests when merging with main. 
@seime anything obvious?

**Comment by seaside1** [comment]
```
ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 1.037 s <<< FAILURE! - in org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest
[ERROR] org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_from  Time elapsed: 0.76 s  <<< ERROR!
java.lang.NullPointerException
	at org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_from(JRuleItemChangeTest.java:49)

[ERROR] org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_no_from_to  Time elapsed: 0.022 s  <<< ERROR!
java.lang.NullPointerException
	at org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_no_from_to(JRuleItemChangeTest.java:40)

[ERROR] org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_from_to  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NullPointerException
	at org.openhab.binding.jrule.internal.triggers.itemchange.JRuleItemChangeTest.testItemChange_from_to(JRuleItemChangeTest.java:67)

```

**Comment by seime** [comment]
@querdenker2k could you rebase and look at the tests?

**Comment by querdenker2k** [comment]
Yes will do it tomorrow

**Comment by seaside1** [comment]
Merging.

**Pull request merged**
