### PR TITLE
add http core actions

### PR DESCRIPTION
**Pull request by querdenker2k**
Add the http core actions.
See https://www.openhab.org/docs/configuration/actions.html#http-actions

### CODE REVIEW

**Comment by seaside1** [comment]
This is a nice addition. Good with a test as well.
I'm behind on reviews would like to test it out a bit, I'll get back shortly as I will have some time the coming days to test things.

**Review by seime — COMMENTED** [review]
README should be updated with new examples

**Comment by querdenker2k** [comment]
> README should be updated with new examples

done

**Comment by querdenker2k** [comment]
Is something missing here?

**Comment by seime** [comment]
Waiting for feedback from @seaside1 since he wanted to test it out a bit before merging.

**Comment by querdenker2k** [comment]
PUSH

**Review by seime — APPROVED** [review]
LGTM

**Comment by seime** [comment]
Merging now to avoid buildup of PRs that requires constant rebasing/conflict resolving.

@seaside1 I think this PR looks good

**Pull request merged**
