### PR TITLE
WIP List JRules inside openhab web interface

### PR DESCRIPTION
**Pull request by seime**
Make rules visible in openHAB and provide easy enabling/disabling

### CODE REVIEW

**Comment by seaside1** [comment]
Rebased and fixed to be up to date with main

**Comment by seime** [comment]
@querdenker2k do you see why some of the ITs are failing?

**Comment by querdenker2k** [comment]
It's because all rules are disabled by default and they are not triggered.
`Adding rule: org.openhab.automation.jrule.rules.user.TestPersistence@421cba65, enabled: false`

**Comment by seaside1** [comment]
Nice. I'll try to review shortly.

**Comment by seaside1** [comment]
Some comments so far, just tested it. I really like this a lot!

- Would it be better to write out what rules are disabled ? Now it is a warning saying "Note X rules are disabled")
- Should we add an annotation to disable a rule?
- Enable / Disable seems to work
- Run now on rule does not seem to work
- JRuleLoadingStatistics could possibly be reset, cleared instead of creating a new instance to follow similar pattern as ruleprovider etc

**Review by seaside1 — APPROVED** [review]
Approved

**Pull request merged**
